# FILENAME: omotetie-dilatazioni.org
# Appunti su omotetie e dilatazioni.

#+BEGIN: insert-latex-macros :file "mathjax-macros-superiori.tex"
#+LATEX_HEADER: \newcommand{\vv}   [1] {\overrightarrow{#1}} % Over-arrow for vectors notation
#+LATEX_HEADER: \newcommand{\norm} [1] {\left|#1\right|} % Norm |x|
#+LATEX_HEADER: \newcommand{\NN}{\mathbb{N}} % Natural numbers
#+LATEX_HEADER: \newcommand{\ZZ}{\mathbb{Z}} % Integers
#+LATEX_HEADER: \newcommand{\QQ}{\mathbb{Q}} % Rational numbers
#+LATEX_HEADER: \newcommand{\RR}{\mathbb{R}} % Real numbers
#+LATEX_HEADER: \newcommand{\CC}{\mathbb{C}} % Complex numbers
#+BEGIN_HTML
\(
\newcommand{\vv}   [1] {\overrightarrow{#1}} % Over-arrow for vectors notation
\newcommand{\norm} [1] {\left|#1\right|} % Norm |x|
\newcommand{\NN}{\mathbb{N}} % Natural numbers
\newcommand{\ZZ}{\mathbb{Z}} % Integers
\newcommand{\QQ}{\mathbb{Q}} % Rational numbers
\newcommand{\RR}{\mathbb{R}} % Real numbers
\newcommand{\CC}{\mathbb{C}} % Complex numbers
\)
#+END_HTML
#+END

* Ometetie
Una *omotetia* di centro $C$ e costante $K \neq 0$ è una funzione che manda ogni
punto $P$ nel punto $P'$ tale per cui vale

\[
\vv{CP'} = K \cdot \vv{CP}
\]

cioè il vettore da $C$ a $P'$ si ottiene moltiplicando il vettore da $C$ a $P$
per la costante $K$.

** Formule per $P'$
Possiamo ottenere le formule per le coordinate $P' = (x', y')$ conoscendo quelle
di $C = (x_C, y_C)$ e di $P = (x, y)$.

Prima di tutto, sappiamo che il vettore $\vv{CP}$ è rappresentato in coordinate
come

\[
\vv{CP} = P - C = (x - x_C,\, y - y_C)
\]

mentre il vettore $\vv{CP'}$ è rappresentato in coordinate come

\[
\vv{CP'} = P' - C = (x' - x_C,\, y' - y_C)
\]

Dunqunque l'uguaglianza $\vv{CP'} = K \cdot \vv{CP}$ diventa proprio

\[
(x' - x_C,\, y' - y_C)
= K \cdot (x - x_C,\, y - y_C)
\]

dove a secondo membro la moltiplicazione di $K$ per il punto significa che
stiamo moltiplicando per $K$ entrambe le coordinate. Quindi l'uguaglianza che
otteniamo è

\[
(x' - x_C,\, y' - y_C)
= ( K (x - x_C),\, K (y - y_C) ).
\]

e ciò significa che questi due punti devono essere lo stesso punto. Ora possiamo
ricordarci che due punti sono uguali precisamente quando hanno le stesse
coordinate, cioè le coordinate $x$ sono uguali in entrambi i punti, cioè

\[
x' - x_C = K (x - x_C)
\]

e le coordinate $y$ sono uguali in entrambi i punti, cioè

\[
y' - y_C = K (y - y_C)
\]

Mettendole assieme, otteniamo il sistema

\[
\left\{
{\begin{array}{l}
 x' - x_C = K (x - x_C) \\
 y' - y_C = K (y - y_C)
 \end{array}}
\right.
\]

e portando a destra $x_C$ nella prima equazone, e $y_C$ nella seconda, otteniamo
infine

\[
\left\{
{\begin{array}{l}
 x' = K (x - x_C) + x_C \\
 y' = K (y - y_C) + y_C
 \end{array}}
\right.
\]

** Omotetia inversa
Dalle formule per l'omotetia, possiamo ricavare l'omotetia inversa isolando $x$
e $y$. Partiamo da

\[
\left\{
{\begin{array}{l}
 x' = K (x - x_C) + x_C \\
 y' = K (y - y_C) + y_C
 \end{array}}
\right.
\]

in entrambe le quazioni facciamo prima i calcoli a secondo membro per scriverle
come

\[
\left\{
{\begin{array}{l}
 x' = K x + x_C (1 - K) \\
 y' = K y + y_C (1 - K)
 \end{array}}
\right.
\]

poi portiamo a destra $Kx$ e $Ky$, portiamo a sinistra $x'$ e $y'$

\[
\left\{
{\begin{array}{l}
 -K x = -x' + x_C (1 - K) \\
 -K y = -y' + y_C (1 - K)
 \end{array}}
\right.
\]

e infine dividiamo entrambi i membri per $-K$ in modo da ottenere

\[
\left\{
{\begin{array}{l}
 x = \frac{1}{K} x' + x_C \frac{K - 1}{K} \\
 y = \frac{1}{K} y' + y_C \frac{K - 1}{K}
 \end{array}}
\right.
\]

** Quando c'è un'omotetia che manda un punto $P$ in un punto $P'$?
In generale, per qualsiasi scelta facciamo per $P$ e $P'$, possiamo sempre
trovare un centro $C = (x_C, y_C)$ e una costante $K$ affinché il punto $P = (x,
y)$ venga mandato in $P' = (x', y')$.

Ma come calcoliamo $C$ e $K$? Per prima cosa, occorre separare due casi.

1) Se $P$ e $P'$ sono lo stesso punto, allora ci sono infinite omotetie, e sono
   tutte di centro $P$ e costante $K$ a piacere. Sono infinite proprio perché
   possiamo scegliere tra infinite $K$ e vanno tutte bene.

2) Se invece $P$ e $P'$ sono diversi, allora sono di nuovo infinite, infatti per
   qualsiasi punto $C$ diverso da entrambi $P$ e $P'$ contenuto nella retta
   $PP'$, possiamo considerare

   \[
   K = \pm \frac{ \overline{CP'} }{ \overline{CP} }
   \]

   in cui mettiamo + se $C$ sta in mezzo a $P$ e $P'$, mentre - se $C$ non sta
   in mezzo.

** Quando c'è un'omotetia di centro fissato che manda un punto $P$ in un punto $P'$? 
Supponiamo che ci sia dato un centro $C = (x_C, y_C)$, allora una omotetia che
manda $P$ in $P'$ esiste soltanto in alcuni casi:

1) Se $P$ e $P'$ sono uguali e coincidono proprio con $C$.

2) Se $C$ è diverso da entrambi $P$ e $P'$ ma è contenuto nella retta $PP'$, e
   in tal caso si prende come coefficiente

   \[
   K = \pm \frac{ \overline{CP'} }{ \overline{CP} }
   \]

   in cui mettiamo $-$ se $C$ sta in mezzo a $P$ e $P'$, mentre $+$ se $C$ non
   sta in mezzo.

* Dilatazioni
Abbiamo visto che per le omotetie di centro $C = (x_C, y_C)$ e costante $K$ si
hanno le formule seguenti per determinare le coordinate del punto $P' = (x',
y')$ in cui viene mandato il punto $P = (x, y)$

\[
\left\{
{\begin{array}{l}
 x' = K (x - x_C) + x_C \\
 y' = K (y - y_C) + y_C
 \end{array}}
\right.
\]

Le *dilatazioni* sono una sorta di generalizzazione delle omotetie, in cui
abbiamo ancora un centro $C = (x_C, y_C)$, ma non c'è solo un $K$ come costante,
bensì ce ne sono due: $K$ e $H$ (entrambe $\neq 0$), che compaiono nelle formule

\[
\left\{
{\begin{array}{l}
 x' = K (x - x_C) + x_C \\
 y' = H (y - y_C) + y_C
 \end{array}}
\right.
\]

Qui si intende che $P = (x, y)$ viene mandato nel punto $P' = (x', y')$.

Nota bene che tutte le omotetie sono dilatazioni, ma in generale non è vero il
viceversa: non tutte le dilatazioni sono omotetie.

** Dilatazione inversa 
Dalle formule per le dilatazioni, possiamo ricavare la dilatazione inversa
isolando $x$ e $y$. Partiamo da

\[
\left\{
{\begin{array}{l}
 x' = K (x - x_C) + x_C \\
 y' = H (y - y_C) + y_C
 \end{array}}
\right.
\]

in entrambe le quazioni facciamo prima i calcoli a secondo membro per scriverle
come

\[
\left\{
{\begin{array}{l}
 x' = K x + x_C (1 - K) \\
 y' = H y + y_C (1 - H)
 \end{array}}
\right.
\]

poi portiamo a destra $Kx$ e $Hy$, portiamo a sinistra $x'$ e $y'$

\[
\left\{
{\begin{array}{l}
 -K x = -x' + x_C (1 - K) \\
 -H y = -y' + y_C (1 - H)
 \end{array}}
\right.
\]

e infine dividiamo entrambi i membri della prima equazione per $-K$, e della
seconda equazione per $-H$, in modo da ottenere

\[
\left\{
{\begin{array}{l}
 x = \frac{1}{K} x' + x_C \frac{K - 1}{K} \\
 y = \frac{1}{H} y' + y_C \frac{H - 1}{H}
 \end{array}}
\right.
\]
** Quando c'è una dilatazione che manda un punto $P$ in un punto $P'$?
In generale, per qualsiasi scelta facciamo per $P$ e $P'$, possiamo sempre
trovare un centro $C = (x_C, y_C)$ e due costanti $K$ e $H$ affinché il punto $P
= (x, y)$ venga mandato in $P' = (x', y')$.

Ma come calcoliamo $C$ e le costanti $K$, $H$? Per prima cosa, occorre separare
due casi.

1) Se $P$ e $P'$ sono lo stesso punto, allora ci sono infinite dilatazioni, e
   sono tutte di centro $P$ e costanti $K$, $H$ a piacere. Sono infinite proprio
   perché possiamo scegliere tra infinite $K$ e $H$, e vanno tutte bene.

2) Se invece $P$ e $P'$ sono diversi, allora sono di nuovo infinite, infatti per
   qualsiasi punto $C$ diverso da entrambi $P$ e $P'$ (qualsiasi!), possiamo
   considerare

   \[
   K = \pm \frac{ \norm{x' - x_C} }{ \norm{x - x_C} },
   \qquad
   H = \pm \frac{ \norm{y' - y_C} }{ \norm{y - y_C} },
   \]

   in cui mettiamo $-$ se $x_C$ (rispettivamente $y_C$) e sta in mezzo a $x$ e
   $x'$ (rispettivamente $y$ e $y'$), mentre mettiamo $+$ se $x_C$
   (rispettivamente $y_C$) non sta in mezzo.

** Quando c'è un'omotetia di centro fissato che manda un punto $P$ in un punto $P'$? 
Supponiamo che ci sia dato un centro $C = (x_C, y_C)$, allora una dilatazione
che manda $P$ in $P'$ esiste soltanto in alcuni casi:

1) Se $P$ e $P'$ sono uguali e coincidono proprio con $C$.

2) Se $C$ è diverso da entrambi $P$ e $P'$, e in tal caso prendiamo come
   coefficienti

   \[
   K = \pm \frac{ \norm{x' - x_C} }{ \norm{x - x_C} },
   \qquad
   H = \pm \frac{ \norm{y' - y_C} }{ \norm{y - y_C} },
   \]

   in cui mettiamo $-$ se $x_C$ (rispettivamente $y_C$) e sta in mezzo a $x$ e
   $x'$ (rispettivamente $y$ e $y'$), mentre mettiamo $+$ se $x_C$
   (rispettivamente $y_C$) non sta in mezzo.
